---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
  labels:
    name: hello
    generated-by: auto-committer
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: hello
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
        - name: test-app
          image: ksatchit/test-k8s-app:sha-2eed22d 
          ports:
            - containerPort: 8080
 
